// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class Area
    {
        public Area()
        {
            Customer = new HashSet<Customer>();
            Unit = new HashSet<Unit>();
        }

        public int AreaId { get; set; }
        public string AreaTlAr { get; set; }
        public int? CityId { get; set; }
        public string AreaTlEn { get; set; }

        public virtual City City { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Unit> Unit { get; set; }
    }
}