// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class Nationality
    {
        public Nationality()
        {
            Customer = new HashSet<Customer>();
            Technician = new HashSet<Technician>();
        }

        public int NationalityId { get; set; }
        public string NationalityTlAr { get; set; }
        public string NationalityTlEn { get; set; }

        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Technician> Technician { get; set; }
    }
}