// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            Receipt = new HashSet<Receipt>();
        }

        public int PaymentMethodId { get; set; }
        public string PaymentMethodTlEn { get; set; }
        public string PaymentMethodTlAr { get; set; }

        public virtual ICollection<Receipt> Receipt { get; set; }
    }
}