// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class ReceiptService
    {
        public ReceiptService()
        {
            Receipt = new HashSet<Receipt>();
        }

        public int ReceiptServiceId { get; set; }
        public string ReceiptServiceTlEn { get; set; }
        public string ReceiptServiceTlAr { get; set; }

        public virtual ICollection<Receipt> Receipt { get; set; }
    }
}