// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class RequestState
    {
        public RequestState()
        {
            Request = new HashSet<Request>();
            RequestLog = new HashSet<RequestLog>();
        }

        public int RequestStateId { get; set; }
        public string RequestStateEn { get; set; }
        public string RequestStateAr { get; set; }

        public virtual ICollection<Request> Request { get; set; }
        public virtual ICollection<RequestLog> RequestLog { get; set; }
    }
}