// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class RequestLog
    {
        public int RequestLogId { get; set; }
        public int RequestId { get; set; }
        public DateTime? VDate { get; set; }

        public int RequestStateId { get; set; }

        public virtual Request Request { get; set; }
        public virtual RequestState RequestState { get; set; }
    }
}