// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace HomeService.Models
{
    public partial class Request
    {
        public Request()
        {
            RequestLog = new HashSet<RequestLog>();
            RequestSpareParts = new HashSet<RequestSpareParts>();
        }

        public int RequestId { get; set; }

        public int CustomerId { get; set; }
        public DateTime? RequestDate { get; set; }
        public DateTime? ScheduleDate { get; set; }
        public int RequestStateId { get; set; }
        [ForeignKey("Contract")]
        public int? ContractId { get; set; }
        public string IssueDescription { get; set; }
        public string Remarks { get; set; }
        public int? TechnicianId { get; set; }
        public string TechDescription { get; set; }
        public string TechDiagnosis { get; set; }
        public string TechFixes { get; set; }
        public string SparePartsDescription { get; set; }
        public bool? IsClosd { get; set; }
        public Double? VisitCost { get; set; }
       
        public int? ServiceCategoryId { get; set; }

        public double Cost { get; set; }

        public bool isPaid { get; set; }
        public string payment_type { get; set; }
        public string PaymentID { get; set; }
        public string Result { get; set; }
        public DateTime? PostDate { get; set; }
        public string TranID { get; set; }
        public string Ref { get; set; }
        public string TrackID { get; set; }
        public string Auth { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Technician Technician { get; set; }
        public virtual RequestState RequestState { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual ICollection<RequestLog> RequestLog { get; set; }
        public virtual ICollection<RequestSpareParts> RequestSpareParts { get; set; }
        public virtual Contract Contract { get; set; }

    }
}