// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class Service
    {
        public Service()
        {
            ContractService = new HashSet<ContractService>();
        }

        public int ServiceId { get; set; }
        public string ServiceTlEn { get; set; }
        public string ServiceTlAr { get; set; }

        public virtual ICollection<ContractService> ContractService { get; set; }
    }
}