        // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class ServiceCategory
    {
        public ServiceCategory()
        {
            Request = new HashSet<Request>();
        }
        public int ServiceCategoryId { get; set; }
        public string ServiceCategoryTlEn { get; set; }
        public string ServiceCategoryTlAr { get; set; }
        public string pic { get; set; }

        public virtual ICollection<Request> Request { get; set; }

    }
}