// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class SparePart
    {
        public SparePart()
        {
            RequestSpareParts = new HashSet<RequestSpareParts>();
        }

        public int SparePartId { get; set; }
        public string SparePartTlEn { get; set; }
        public string SparePartTlAr { get; set; }
        public double? Price { get; set; }
        public string SparePartDescrition { get; set; }
        public virtual ICollection<RequestSpareParts> RequestSpareParts { get; set; }


    }
}