// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class Technician
    {
        public Technician()
        {
            Request = new HashSet<Request>();
        }
        public int TechnicianId { get; set; }
        public string FullNameEn { get; set; }
        public string CivilId { get; set; }
        public string FullAddress { get; set; }
        public int? NationalityId { get; set; }
        public string PassportNo { get; set; }
        public string Mobile { get; set; }
        public string Tele { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
        public string FullNameAr { get; set; }
        public string Pic { get; set; }
        public string DeviceId { get; set; }
         public bool? IsAndroiodDevice { get; set; }
         public bool? IsIosDevice { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual ICollection<Request> Request { get; set; }


    }
}