// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class UnitGroup
    {
        public UnitGroup()
        {
            Unit = new HashSet<Unit>();
        }

        public int UnitGroupId { get; set; }
        public string UnitGroupTlAr { get; set; }
        public string UnitGroupTlEn { get; set; }
        public int? UnitGroupOrderIndex { get; set; }

        public virtual ICollection<Unit> Unit { get; set; }
    }
}