// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeService.Models
{
    public partial class Unit
    {
        public Unit()
        {
            Contract = new HashSet<Contract>();
        }

        public int UnitId { get; set; }
        public int UnitGroupId { get; set; }
        public int? AreaId { get; set; }
        public string UnitTile { get; set; }
        public string Block { get; set; }
        public string Avenue { get; set; }
        public string Street { get; set; }
        public string BuildingNo { get; set; }
        public string Floor { get; set; }
        public string Flat { get; set; }
        public string Remarks { get; set; }

        public virtual Area Area { get; set; }
        public virtual UnitGroup UnitGroup { get; set; }
        public virtual ICollection<Contract> Contract { get; set; }
    }
}